# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: license
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  license:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        run: |
          header="Copyright (c) 2018-$(date +%Y) Yegor Bugayenko"
          failed="false"
          while IFS= read -r file; do
            if ! grep -q "${header}" "${file}"; then
              failed="true"
              echo "⚠️ Copyright header is not found in: ${file}"
            else
              echo "File looks good: ${file}"
            fi
          done < <(find . -type f \( \
            -name "Dockerfile" -o \
            -name "LICENSE.txt" -o \
            -name "Makefile" -o \
            -name "Rakefile" -o \
            -name "*.sh" -o \
            -name "*.rb" -o \
            -name "*.fe" -o \
            -name "*.yml" \
            \) -print)
          if [ "${failed}" = "true" ]; then
            exit 1
          fi
