---
name: xcop
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  xcop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: g4s8/xcop-action@master
        with:
          files: '**/*.xml'
